### DISCUSSION TITLE
Recipe for Azure Pipelines?

### DISCUSSION THREAD

**Discussion by BeyondEvil** [direnv/direnv#1091] [Q&A]
Is there a recipe for using direnv with Azure Pipelines?

We're currently doing this:

```yaml
trigger:
  - '*'

resources:
  containers:
    - container: python
      image: python:3.10

variables:
  CI: 'true'

jobs:
  - job: lint
    displayName: Lint code
    container: python
    steps:
      - bash: |
          mkdir -p "${HOME}"/.local/bin
          echo "##vso[task.prependpath]$HOME/.local/bin"
        displayName: Add .local/bin to PATH

      - bash: |
          export version="v2.32.2"  # version of direnv to install
          curl -sfL https://direnv.net/install.sh | bash
          direnv allow
        displayName: Install direnv

      - bash: |
          eval "$(direnv export bash)"
          pre-commit run --all-files --show-diff-on-failure
        displayName: Run pre-commit
``` 

But similar to #903 we have to run `eval "$(direnv export bash)"` every time. 😊
