### ISSUE TITLE
Allow flexible whitelist by allowing `~/` or `$HOME` expansion

### ISSUE THREAD

**Issue by erikw** [direnv/direnv#926]
**Is your feature request related to a problem? Please describe.**
Currently I would need to have this in my `$XDG_CONFIG_HOME/direnv/direnv.toml`:

```toml
[whitelist]
prefix = [ "/Users/erikw/src/something/" ]
```

however as dotfiles are share across different system which have different directory hierchy e.g. Linux having `/home` instead of `/Users` like macOS, I would need to adapt the `direnv.toml` per system type.

**Describe the solution you'd like**
Solutions could be
```toml
[whitelist]
prefix = [ "~/src/something/" ]
```

or

```toml
[whitelist]
prefix = [ "$HOME/src/something/" ]
```

**Additional context**
Separate issue -- we should really move away from the dated whitelist terminology and adopt **allowlist** instead!
